---
title: "Manova Repeated Measures"
author: ""
date: ""
output:
  html_document:
    df_print: paged
    toc: TRUE
    toc_float: TRUE
---

Test Manova Repeated Measures on Dog Data

#libraries
```{r}
library(ggplot2)
library(reshape2)
library(dplyr)
library(MASS)
```

# Read data
```{r}
#read the input data
bugs = read.table("../data/insect.txt", sep = " ",
	col.names = c("bug","w.j1","w.j2","w.ae"),
	stringsAsFactors = TRUE)
bugs
```

```{r}
bugs.lda = lda(formula = bug ~ w.j1 + w.j2 + w.ae, method = "moment",
         data = bugs, 
         prior = c(1,1)/2)
		 
predict(bugs.lda, data.frame(w.j1 = c(194), w.j2 = c(124), w.ae = c(49)))$posterior

e = exp(1)
(e^202.359)/((e^202.359)+(e^205.219))

```

---
title: "L10 - LDA"
author: ""
date: ""
output:
  html_document:
    df_print: paged
    toc: TRUE
    toc_float: TRUE
---
LDA on Insect Data

#libraries
```{r}
library(ggplot2)
library(reshape2)
library(dplyr)
library(MASS)
```

[R discriminant](http://uc-r.github.io/discriminant_analysis)

# Read data
```{r}
#read the input data
bugs = read.table("../data/insect.txt", sep = " ",
	col.names = c("type", "w1", "w2", "wae"),
	stringsAsFactors = TRUE)
bugs
```

# LDA
```{r}
#fit the LDA with equal prior prob
#bugs.lda = lda(formula = type ~ ., data = bugs)
bugs.lda = lda(formula = type ~ ., data = bugs, prior = c(1,1)/2)
#predict for new observation
predict(bugs.lda, data.frame(w1 = c(194), w2 = c(124), wae = c(49)))
#compare with prob from notes (does not exactly match?)
exp(202.359)/(exp(202.359)+exp(205.219))
```
