---
title: "Split-Plot Repeated Measures"
author: ""
date: ""
output:
  html_document:
    df_print: paged
    toc: TRUE
    toc_float: TRUE
---

Test Split-Plot Anova Repeated Measures on Dog Data

#libraries
```{r, imports1}
library(ggplot2)
library(reshape2)
library(dplyr)
library(lme4)
```

# Read data
```{r}
#read the input data
dogs = read.table("../data/dog1.txt", sep = " ",
	col.names = c("treat", "dog", "p1", "p5", "p9", "p13"),
	stringsAsFactors = TRUE)
#treatment and dog should be a factor
dogs$treat = factor(paste0("treat",dogs$treat))
dogs$dog = factor(paste0("d",dogs$dog))
#make data tall-skinny on time
dogs_ts = melt(dogs, id.vars = c("treat","dog"), variable.name = "time", measure.vars = c("p1","p5","p9","p13"), value.name = "k")
#replace period names with times by stripping off 'p'
#dogs_ts$time = as.numeric(substr(dogs_ts$time,2,100))
dogs_ts
```


```{r}
res1 = aov(k ~ treat*time + Error(dog:treat), data = dogs_ts)
summary(res1)
res2 = aov(k ~ treat + time + Error(dog:treat), data = dogs_ts)
summary(res2)
```